Diagnostics:
  ClangTidy:
    Add:
      [
        # performance-*,
        # bugprone-*,
        # portability-*,
        # modernize-*,
        misc-unused-parameters,
      ]
    Remove: modernize-use-trailing-return-type
    CheckOptions:
      WarnOnFloatingPointNarrowingConversion: false